server:
  port: 8090

spring:
  application:
    name: social-service
  profiles:
    active: @spring.profiles.active@
  data:
    web:
      pageable:
        one-indexed-parameters: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  messages:
    basename: messages
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${CALLBACK_URL:http://localhost:${client.port}/google/call-back}
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  mail:
    duration: 300
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



client:
  port: 3000
  url: ${SOCIAL_URL:http://localhost:${client.port}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO