spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_social_prod
    username: root
    password: 12042002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  base64-secret: prod
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 864000

