services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_URL}
      - MYSQL_ROOT=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default

  social-service:
    container_name: social-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - default

networks:
  default:
    name: social-service

volumes:
  mysql_data: